// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnc4Cbnu4esH16-4mK9gPAEt1W_0DDgps',
    appId: '1:449074596521:web:1c6606a9de6acc2c7c37b8',
    messagingSenderId: '449074596521',
    projectId: 'portfolio-5a8af',
    authDomain: 'portfolio-5a8af.firebaseapp.com',
    storageBucket: 'portfolio-5a8af.firebasestorage.app',
    measurementId: 'G-RN30R4MQTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACXHlqZomxmB9SZpU1baKDh1RuFLZ9RQM',
    appId: '1:449074596521:android:a765978f15f9f2dc7c37b8',
    messagingSenderId: '449074596521',
    projectId: 'portfolio-5a8af',
    storageBucket: 'portfolio-5a8af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp5tP23dkOzrFmiRudwrppsjN1eGmEj74',
    appId: '1:449074596521:ios:6200007198a74afe7c37b8',
    messagingSenderId: '449074596521',
    projectId: 'portfolio-5a8af',
    storageBucket: 'portfolio-5a8af.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp5tP23dkOzrFmiRudwrppsjN1eGmEj74',
    appId: '1:449074596521:ios:6200007198a74afe7c37b8',
    messagingSenderId: '449074596521',
    projectId: 'portfolio-5a8af',
    storageBucket: 'portfolio-5a8af.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
}
