// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGN3vlW7nVM94eIRntnKye8l2JKRBqX5w',
    appId: '1:302426228688:web:e624ccc5feb8d97eb2dbd5',
    messagingSenderId: '302426228688',
    projectId: 'profilo-2f157',
    authDomain: 'profilo-2f157.firebaseapp.com',
    storageBucket: 'profilo-2f157.firebasestorage.app',
    measurementId: 'G-7CYDNH7C1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2cBiOQgJgU3uBqY4S9KPf8i6BIsTmWWg',
    appId: '1:302426228688:android:0ff0ce434a81f5c3b2dbd5',
    messagingSenderId: '302426228688',
    projectId: 'profilo-2f157',
    storageBucket: 'profilo-2f157.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqbKP1YrQ2vjcEeS_FMHMDixtgOoRZnq4',
    appId: '1:302426228688:ios:90d7147c2bf462e2b2dbd5',
    messagingSenderId: '302426228688',
    projectId: 'profilo-2f157',
    storageBucket: 'profilo-2f157.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqbKP1YrQ2vjcEeS_FMHMDixtgOoRZnq4',
    appId: '1:302426228688:ios:90d7147c2bf462e2b2dbd5',
    messagingSenderId: '302426228688',
    projectId: 'profilo-2f157',
    storageBucket: 'profilo-2f157.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGN3vlW7nVM94eIRntnKye8l2JKRBqX5w',
    appId: '1:302426228688:web:bb28129b39823997b2dbd5',
    messagingSenderId: '302426228688',
    projectId: 'profilo-2f157',
    authDomain: 'profilo-2f157.firebaseapp.com',
    storageBucket: 'profilo-2f157.firebasestorage.app',
    measurementId: 'G-DKH1H0CF5E',
  );
}
